### PR TITLE
Make sure that parsedcode is of type Expr

### LINKED ISSUE #8: Loosen requirement that parsed code is of type Expr
I have started using the dependency explorer and the expression explorer for a project of mine and it has been quite fun.

However, I did notice a slight problem, which is that if you have a cell with contents "notebook", then `updated_topology` breaks.

MWE:
```julia
import PlutoDependencyExplorer as PDE
struct SimpleCell <: PDE.AbstractCell
    code
end

notebook = SimpleCell.([
    "x + y"
    "x = 1"
    "y = x + 2"
    "notebook"  # this cell breaks updated_topology
])

empty_topology = PDE.NotebookTopology{SimpleCell}();

topology = PDE.updated_topology(
    empty_topology,
    notebook, notebook;
    get_code_str = c -> c.code,
    get_code_expr = c -> Meta.parse(c.code),
)
```
```
ERROR: MethodError: no method matching PlutoDependencyExplorer.ExprAnalysisCache(::String, ::Symbol)

Closest candidates are:
  PlutoDependencyExplorer.ExprAnalysisCache(::Any, ::Any, ::Any, ::Any, ::Any)
   @ PlutoDependencyExplorer C:\Users\jackn\.julia\packages\PlutoDependencyExplorer\vDlZV\src\Topology.jl:5
  PlutoDependencyExplorer.ExprAnalysisCache(::String, ::Expr, ::ExpressionExplorer.UsingsImports, ::Bool, ::Union{Nothing, UInt64})
   @ PlutoDependencyExplorer C:\Users\jackn\.julia\packages\PlutoDependencyExplorer\vDlZV\src\Topology.jl:5
  PlutoDependencyExplorer.ExprAnalysisCache(::String, ::Expr)
   @ PlutoDependencyExplorer C:\Users\jackn\.julia\packages\PlutoDependencyExplorer\vDlZV\src\Topology.jl:12

Stacktrace:
 [1] updated_topology(old_topology::PlutoDependencyExplorer.NotebookTopology{…}, notebook_cells::Vector{…}, updated_cells::Vector{…}; get_code_str::var"#1#3", get_code_expr::var"#2#4", get_cell_disabled::Function)
   @ PlutoDependencyExplorer C:\Users\jackn\.julia\packages\PlutoDependencyExplorer\vDlZV\src\TopologyUpdate.jl:43
 [2] top-level scope
   @ REPL[7]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by JackDevine**
Fixes #8 

Sorry for the delay and thanks again for your advice in the linked issue.

### CODE REVIEW

File: src/TopologyUpdate.jl [hunk 1]
```diff
@@ -39,7 +39,7 @@ function updated_topology(
 		new_code_str = get_code_str(cell)
 		
 		if old_code.code !== new_code_str
-			parsedcode = get_code_expr(cell)
```
Comment (fonsp) [inline src/TopologyUpdate.jl:42]: Can you do the wrap only if the expression is not already a `Expr`?

**Review by fonsp — CHANGES_REQUESTED** [review]

**Comment by JackDevine** [comment]
Thanks for making those changes @fonsp ! Doing a few local tests, I can see that the results are different if you always wrap the expressions.

Do you think that the CI failures on Julia latest are unrelated?
